name: Windows

on: [push, pull_request]

jobs:
  clang-cl-12-x64:

    runs-on: windows-latest



    env:
      VCPKG_DEFAULT_TRIPLET: x64-windows
      cmake_extra: '-DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_C_COMPILER_LAUNCHER=buildcache -DCMAKE_CXX_COMPILER_LAUNCHER=buildcache'

    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'apache/qpid-proton'
          ref: '0.36.0'
          path: 'qpid-proton'

      - uses: actions/checkout@v2
        with:
          path: 'qpid-dispatch'

      # TODO review this thing, I'm just dropping random code in here
      - uses: mikehardy/buildcache-action@v1

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          architecture: x64

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools wheel tox

#      - name: Install Windows dependencies
#        if: runner.os == 'Windows'
#        run: |
#          choco install -y swig --version=4.0.1
#          vcpkg install jsoncpp
#          vcpkg integrate install


      - name: proton configure
        run: cmake -S . -B build -G "Visual Studio 16 2019" -A x64 -DCMAKE_INSTALL_PREFIX=install -DBUILD_BINDINGS=python -DBUILD_EXAMPLES=OFF -DBUILD_TESTING=OFF -DENABLE_FUZZ_TESTING=OFF -DCMAKE_C_COMPILER_LAUNCHER=buildcache -DCMAKE_CXX_COMPILER_LAUNCHER=buildcache
        working-directory: 'qpid-proton'

      - name: proton make
        run: cmake --build build --config RelWithDebInfo --parallel 4
        working-directory: 'qpid-proton'

      - name: proton install
        run: cmake --install build --config RelWithDebInfo
        working-directory: 'qpid-proton'

      - name: proton install python wheel
        run: python -m pip install D:/a/qpid-dispatch/qpid-dispatch/qpid-proton/build/python/pkgs\python_qpid_proton-0.36.0-cp39-cp39-win_amd64.whl


      - name: dispatch configure
        run: cmake -S . -B build -G "Visual Studio 16 2019" -A x64 -T ClangCL -DProton_DIR=D:/a/qpid-dispatch/qpid-dispatch/qpid-proton/install/lib/cmake/Proton -DCMAKE_INSTALL_PREFIX=install -DCONSOLE_INSTALL=OFF -DCMAKE_C_COMPILER_LAUNCHER=buildcache -DCMAKE_CXX_COMPILER_LAUNCHER=buildcache
        working-directory: 'qpid-dispatch'

      - name: dispatch make
        run: cmake --build build --config RelWithDebInfo --parallel 4
        working-directory: 'qpid-dispatch'

      - name: dispatch install
        run: cmake --install build --config RelWithDebInfo
        working-directory: 'qpid-dispatch'

      # https://ibob.bg/blog/2018/12/16/windows-rpath/
      - name: copy dlls (cmake has to do this in the future)
        run: |
          cp qpid-proton/install/bin/qpid-proton-core.dll qpid-dispatch/build/router/RelWithDebInfo
          cp qpid-proton/install/bin/qpid-proton-proactor.dll qpid-dispatch/build/router/RelWithDebInfo

      - name: dispatch test
#        run: ctest -j 2 -C RelWithDebInfo --output-on-failure
        run: ctest -j 1 -C RelWithDebInfo -VV
        working-directory: 'qpid-dispatch/build'

#  clang-cl-10-x86:
#
#    runs-on: windows-latest
#
#    steps:
#      - uses: actions/checkout@v1
#      - name: cmake
#        run: cmake -S . -B build -G "Visual Studio 16 2019" -A Win32 -T ClangCL
#      - name: build
#        run: cmake --build build --config RelWithDebInfo --parallel 10
#      - name: test
#        run: cd build; ctest -j 2 -C RelWithDebInfo --output-on-failure
